version: '3'

tasks:
  build:
    cmds:
      - go build
  gen:
    preconditions:
      -  go install github.com/tinylib/msgp@latest
    cmds:
      - go generate
  run:
    deps: [gen, build]
    cmds:
      - ./godb
    env:
      GODB_LOG_PATH: /tmp/logs